### PR TITLE
Use math/rand's global random generator instead of creating a new one

### PR DESCRIPTION
**Pull request by PatrickDropbox**
this ensures third party packages also benefit from the change.

### CODE REVIEW

**Comment by msolo-dropbox** [comment]
If you want to just export functions, you can just do:

var (
  Seed = rand.Seed
  Int63n = rand.Int63n
)

No need to write a function.

**Comment by PatrickDropbox** [comment]
The godoc won't look as pretty =P

**Comment by PatrickDropbox** [comment]
I guess it's not that pretty right now either.  I'll switch over.

**Comment by msolo-dropbox** [comment]
More just letting you know you can be more lazy  :-)

**Comment by PatrickDropbox** [comment]
s/globalRand/rand is lazier

**Comment by msolo-dropbox** [comment]
:)

**Pull request merged**
